#datasources
spring.datasource.url=jdbc:postgresql://localhost:5432/db_book?currentSchema=sc_book&ssl=false
spring.datasource.username=admin
spring.datasource.password=1234
spring.datasource.driver-class-name=org.postgresql.Driver


spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
server.port=8081

app.jwt.secret=ThisIsMyVeryLongJwtSecretKeyForSpringBootApplicationHS512AlgorithmSecurity2026AndMoreCharacters1234567890

app.jwt.expiration-in-ms=86400000

authentication.internal-api-key=InternalApiKey1234!